// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgnBYu3R99gS4Ps7D55d47tlkrVGver2M',
    appId: '1:326142010086:web:4316f02401a3988d2f1127',
    messagingSenderId: '326142010086',
    projectId: 'bpkar-e6de9',
    authDomain: 'bpkar-e6de9.firebaseapp.com',
    storageBucket: 'bpkar-e6de9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDknNfv0bFk--jfNzaLWeDXVfqUPmeHij4',
    appId: '1:326142010086:android:f016bb169aeb9d742f1127',
    messagingSenderId: '326142010086',
    projectId: 'bpkar-e6de9',
    storageBucket: 'bpkar-e6de9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBi094hJR9o2-leMxkex_KOlIkFvK2WwhY',
    appId: '1:326142010086:ios:60ebd9fbcbb2f4f32f1127',
    messagingSenderId: '326142010086',
    projectId: 'bpkar-e6de9',
    storageBucket: 'bpkar-e6de9.firebasestorage.app',
    iosBundleId: 'com.example.mobileApp',
  );
}
