name: Flutter Auto Format

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read  
  actions: write   
  pull-requests: write  
  
jobs:
  format:
    name: Auto Format Dart Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.x"

      - name: Instalar dependências
        run: flutter pub get

      - name: Formatar código
        run: dart format .

      - name: Commit das mudanças (se houver)
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Format code automatically" || echo "No changes to commit"
          git push https://${{ secrets.GH_TOKEN }}@github.com/Grupo-6-bpk/mobile-app.git HEAD:master
